[package]
name = "async-priority-limiter"
version = "0.1.0"
edition = "2024"
license = "ISC"

[dependencies]
async-throttle = "0.3.2"
flume = "0.11.1"
futures = "0.3.31"
tokio = { version = "1.45.0", features = ["full"] }

[dev-dependencies]
itertools = "0.14.0"

